deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash scripts/deploy-stage.sh staging
    on:
      branch: master
  # deploy master to production
  # - provider: script
  #   script: bash scripts/deploy-stage.sh production
  #   on:
  #     branch: master