
apiVersion: v1
kind: Pod
metadata:
  name: command-demo-react-withoutpath
  labels:
    purpose: demonstrate-command-react
spec:
  containers:
  - name: react-command-demo
    image: dockerfonseka/sample-app
    volumeMounts:
    - name : node-storage
      mountPath: /usr/src/app
    - name : node-modules
      mountPath: /usr/src/app/node_modules
  volumes:
    - name : node-storage
      emptyDir : {}
    - name : node-modules
      emptyDir : {}
  restartPolicy: OnFailure

